version: '3.9'

services:
  web:
    build:
      context: ./app
    container_name: django_app
    command: >
      sh -c "python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./app:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    environment:
      - DEBUG=True
      - DATABASE_URL=postgres://postgres:password@db:5432/postgres

  db:
    image: postgres:14
    container_name: postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data





  redis:
    image: redis:alpine
    ports:
      - 6379:6379
    restart: always 

  celery_worker:
    build: ./app
    command: celery -A app worker --loglevel=info
    volumes:
      - ./app:/app
    env_file:
      - ./app/.env.dev
    depends_on:
      - db
      - redis
    restart: always

  celery_beat:
    build: ./app
    command: celery -A app beat --loglevel=info
    volumes:
      - ./app:/app
    env_file:
      - ./app/.env.dev
    depends_on:
      - db
      - redis
      - celery_worker
    restart: always

volumes:
  postgres_data:
